#!/usr/bin/env python3

# Very simple and primitive "jsonschema"-like script supposed
# to validate a yaml data file against a certain yaml schema.

import sys
import yaml
import jsonschema
import json

if len(sys.argv) != 3:
	print(f"Usage: {__file__} SCHEMA_FILE DATA_FILE")
	exit(1)

schema_file = sys.argv[1]
data_file   = sys.argv[2]

schema = yaml.safe_load(open(schema_file).read())
data   = yaml.safe_load(open(data_file).read())

jsonschema.validate(data, schema)

print(json.dumps(data))
