#!/bin/sh

# CFR (Class File Reader) - Another Java Decompiler
# https://github.com/leibnitz27/cfr
#
# It's implemented entirely in Java 6 and able to decompile modern Java
# features - including much of Java 9, 12, and 14.
#
# This file is wrapper for CFR to simplify its invocation.
# It looks for the latest Jar file in the same directory.

set -o errexit
set -o pipefail

MYDIR="$( dirname "$0" )"
JARFILE="$( ls -r "$MYDIR"/cfr-*.jar | head -1 )"

[ "$OSTYPE" = "cygwin" ] \
&& JARFILE="$( cygpath -m "$JARFILE" )"

java -jar "$JARFILE" "$@"
