#!/bin/sh

# =========================================================================
#
# Validate the domain certificate
#
# Copyright (C) 2023 Ildar Shaimordanov
# MIT License
#
# =========================================================================

# +++
#
# # NAME
#
# `sslage` - validate the domain certificate
#
# # SYNOPSIS
#
#     sslage [-v] HOST[:PORT]
#
# # DESCRIPTION
#
# * Displays the time period when the certificate is valid
# * Estimates the total number of days when the certificate is valid
# * Estimates the number of days left until the certificate expires
#
# ---

# =========================================================================

ME="$( basename "$0" )"

VERBOSE=""

# =========================================================================

print_usage() {
	warn "\
Usage: $ME [-v] HOST[:PORT]
Display age of the host SSL certificate.
If no port specified, :443 is assumed.
Use the -v option to see the certificate details.
"
}

# =========================================================================

die() {
	warn "${*-Died!}"
	exit 1
}

warn() {
	info "${*-Warning!}" >&2
}

info() {
	printf '%s\n' "$@"
}

# =========================================================================

while getopts ":v" opt
do
	case "$opt" in
	v ) VERBOSE=1 ;;
	* ) die "Illegal option: $OPTARG" ;;
	esac
done

shift $(( OPTIND-1 ))

[ $# -gt 0 ] || {
	print_usage
	exit 1
}

# =========================================================================

# Uncomment one of the following line for testing under BusyBox or Cygwin
# with the curl embedded to Windows
#PATH="C:/Windows/System32;$PATH"
#PATH="/cygdrive/c/Windows/System32:$PATH"

AGE=""

for n in openssl curl
do
	command -v $n >/dev/null && {
		AGE="$n"
		break
	}
done

[ -n "$AGE" ] || die "No proper tool"

# =========================================================================

# +++
#
# ## Capturing the certificate dates
#
# `openssl` is the standard tool for testing certificates. That's the
# simplest way to find out the certificate time period.
#
# There is alternative way to recognize the SSL certificate
# details. Calling `curl -v` allows us to capture the full information
# about SSL negotiation and extract some details about the certificate.
#
# The `-v` option is used for verbosity in both cases: to show the
# certificate details and to display error if something goes wrong.
#
# ---

age() {
	[ "$1" = "${1%:*}" ] && set -- "$1:443"
	age_$AGE "$1"
}

age_openssl() {
	[ -n "$VERBOSE" ] || exec 2>/dev/null

	openssl s_client -servername "${1%:*}" -connect "$1" </dev/null \
	| openssl x509 -dates -noout
}

age_curl() {
	full_info="$( age_curl_full_info "$1" )"
	cert_info="$( echo "$full_info" | age_curl_cert_info )"

	# Exit immediately if no certificate information is captured. When
	# verbosity is enabled, SSL negotiation is printed.
	[ -n "$cert_info" ] || {
		[ -n "$VERBOSE" ] && warn "$full_info"
		return 1
	}

	# Print the certificate details, when verbosity is on.
	[ -n "$VERBOSE" ] && warn "$cert_info"

	# Extract dates and convert output to the openssl-like view.
	echo "$cert_info" \
	| sed -n \
	's/.*start date: /notBefore=/p; s/.*expire date: /notAfter=/p'
}

age_curl_full_info() {
	curl -s -v -I "https://$1" 2>&1 \
	| grep '^\*'
}

age_curl_cert_info() {
	sed -n \
	'/^\* Server certificate:$/ { p; :a; n; /^\* [ \t]/p; ba }'
}

# =========================================================================

# +++
#
# ## Calculate the certificate age using `awk` or pure shell
#
# The certificate age is estimated as the number of the whole days. So,
# if today is the last day of the certificate validity, it's assumed
# that the certificate is expired already. I tried to implement the
# script POSIX-compliant as much as possible.
#
# Initially it's been the shell script with `awk` inline script having
# almost 50% of the script size. Later I improved it and added the
# function validating the certificate age implemented in pure shell. I
# decided to keep the previous `awk`-based implementation. Just for fan.
#
# ---

validate_age() {
	validate_age_sh
}

validate_age_sh() {
	s1=""
	s2=""

	while IFS='=' read -r m t
	do
		[ "$m" = "notBefore" ] || [ "$m" = "notAfter" ] || continue

		s="$( date -d "${t% *}" -u +%s )"

		case "$m" in
		notBefore ) t1="$t" ; s1="$s" ;;
		notAfter  ) t2="$t" ; s2="$s" ;;
		esac
	done

	if [ -z "$s1" ] || [ -z "$s2" ]
	then
		die "Error: No data to validate"
	fi

	s0="$( date -u +%s )"
	n="$( days "$s0" "$s2" )"

	if [ "$n" -gt "0" ]
	then
		m="Left"
	else
		m="Expired"
		n="$(( -n ))"
	fi

	echo "Since: $t1"
	echo "Until: $t2"
	echo "Days: $( days "$s1" "$s2" )"
	echo "$m: $n"
}

days() {
	echo "$(( ($2 - $1) / 86400 ))"
}

validate_age_awk() {
	awk -v s0="$( date -u +%s )" -F= '
/notBefore/ { t1 = $2 }
/notAfter/  { t2 = $2 }

# Workaround to enable the script working properly in busybox also,
# because of the limited set of the supported TIME formats there.
function bb_compat(v) { sub(/ \S+$/, "", v); return v }

function epoch(v) { "date -d\"" v "\" -u +%s" | getline v; return v }

function days(v1, v2) { return int((v2 - v1) / 86400) }

END {
	if ( ! t1 || ! t2 ) {
		print "Error: No data to validate" > "/dev/stderr"
		exit 1
	}

	print "Since:", t1
	print "Until:", t2

	s1 = epoch(bb_compat(t1))
	s2 = epoch(bb_compat(t2))

	print "Days:", days(s1, s2)

	n = days(s0, s2)
	if ( n > 0 ) {
		print "Left:", n
	} else {
		print "Expired:", -n
	}
}'
}

# =========================================================================

age "$1" | validate_age

# =========================================================================

# +++
#
# # SEE ALSO
#
# * https://github.com/shakibamoshiri/curly
# Their "check SSL date" does almost the same thing the current project
# implements.
#
# # LICENSE
#
# Copyright 2023 Ildar Shaimordanov
#
#     MIT License
#
# ---

# =========================================================================

# EOF
