#!/usr/bin/env bash

[ -n "$1" ] || {
	echo "No file for edit" >&2
	exit 1
}

WINPTY_HOME='C:\PROGS\vendors\winpty\cygwin'
WINPTY_HOME="$( cygpath "$WINPTY_HOME" )"

FAR_HOME='C:\PROGS\vendors\Far3'
FAR_HOME="$( cygpath "$FAR_HOME" )"

filename="$( cygpath -w "$1" )"

"$WINPTY_HOME/console" "$FAR_HOME/Far" /e "$filename"

