#!/usr/bin/env bash

# =========================================================================

# Check if current directory is a Git repository
# https://stackoverflow.com/a/2180367/3627676
git_check_is_git() {
	[ -d .git ] \
	|| git rev-parse --git-dir > /dev/null 2>&1
}

# How to see all local commits which are not pushed to the remote branch?
# https://stackoverflow.com/a/30601779/3627676
#
# Finding what branch a git commit came from
# https://stackoverflow.com/a/2707110/3627676
git_check_unpushed() {
	git log --branches --not --remotes \
	| sed -n '/^commit / s/.* //p' \
	| while read n
	do
		git branch --contains "$n"
	done \
	| sort -u \
	| sed 's/..//'
}

# =========================================================================

git_bunch() {
	local bunch_dir

	bunch_dir="$1"
	shift

	if [ $# -eq 0 ]
	then
		ls "$bunch_dir"
		return $?
	fi

	find "$bunch_dir" -maxdepth 1 -type d \
	| while read f
	do
		(
			cd "$f"
			git_check_is_git || exit

			echo "#### $f"

			case "$1" in
			unpushed | check-unpushed | check_unpushed )
				git_check_unpushed
				;;
			* )
				git "$@"
				;;
			esac
		)
	done
}

# =========================================================================

git_bunch "$@"

# =========================================================================

# EOF
