#!/usr/bin/env bash

# =========================================================================

# Check if current directory is a Git repository
# https://stackoverflow.com/a/2180367/3627676
git_check_is_git() {
	[ -d .git ] \
	|| git rev-parse --git-dir > /dev/null 2>&1
}

# How to see all local commits which are not pushed to the remote branch?
# https://stackoverflow.com/a/30601779/3627676
#
# Finding what branch a git commit came from
# https://stackoverflow.com/a/2707110/3627676
git_check_unpushed() {
	git log --branches --not --remotes \
	| sed -n '/^commit / s/.* //p' \
	| while read n
	do
		git branch --contains "$n"
	done \
	| sort -u \
	| sed 's/..//'
}

# =========================================================================

for f in *
do
	[ -d "$f" ] || continue

	echo "# $f"
	(
		cd "$f"
		git_check_is_git \
		&& git_check_unpushed
	)
done

# =========================================================================

# EOF
