#!/bin/sh

# =========================================================================
#
# Copyright (C) 2024 Ildar Shaimordanov
# MIT License
#
# =========================================================================

print_usage() {
	echo "\
Usage: bulkping [OPTIONS] [HOST ...]
Ping multiple targets in parallel.

Options
	-f FILE	Read hosts from the FILE instead of stdin
	-m MAX	Ping at most MAX hosts at a time (defaults to 10)
"
}

# =========================================================================

MAX_PINGS=10
PING_FILE=''

bulkping() {
	# Windows has its own version of ping utility with its own set
	# of options. Let's take it into account and provide all the
	# arguments correctly. It affects on execution under BusyBox.
	# shellcheck disable=SC2016
	xargs ${MAX_PINGS:+-P "$MAX_PINGS"} -r ${PING_FILE:+-a "$PING_FILE"} \
	-IX sh \
	-c 'ping -n $1 1 "X" >/dev/null 2>&1 || { echo "X" >&2 ; exit 1 ; }' \
	- "$( case "$( uname -s )" in Window* ) ;; * ) echo '-c' ;; esac )"
}

# =========================================================================

die() {
	warn "$*"
	exit 1
}

warn() {
	echo "$*" >&2
}

# =========================================================================

while getopts ':f:m:' arg
do
	case "$arg" in
	f ) PING_FILE="$OPTARG" ;;
	m ) MAX_PINGS="$OPTARG" ;;
	: ) die "Argument is required: -$OPTARG" ;;
	* ) die "Bad option: -$OPTARG" ;;
	esac
done

shift $(( OPTIND - 1 ))

[ -t 0 ] && [ $# -eq 0 ] && [ -z "$PING_FILE" ] && {
	print_usage
	exit
}

if [ $# -eq 0 ]
then
	bulkping
else
	# Command line arguments have higher priority even if the file
	# is specified. So we clean the variable holding the filename
	# to apply the arguments only.
	PING_FILE=''
	printf '%s\n' "$@" | bulkping
fi

# =========================================================================

# +++
#
# Read hosts from stdin, file or command line and do ping towards them in
# parallel. Print to stderr the hosts that return errors when ping them.
#
# Example:
#
#     printf '%s\n' goo.gl goog.le | bulkping
#
# Requirements:
#
# * sh
# * uname
# * xargs
# * ping
#
# ---

# =========================================================================

# EOF
