#!/bin/sh

# =========================================================================
#
# Stop printing the rest of each line that length exceeds a terminal width
#
# Copyright (C) 2024, 2026 Ildar Shaimordanov
# MIT License
#
# =========================================================================

[ -t 0 ] &&  {
	echo "\
Stop printing lines longer than a terminal width
Usage: ... | cap
"
	exit
}

# =========================================================================

# Bypass truncation if running without a TTY (cron, nohup)
[ -c /dev/tty ] || { cat - ; exit ; }

cut -c 1-$(
	exec 2>/dev/null

	command -v tput >/dev/null \
	&& tput cols \
	&& exit

	command -v stty >/dev/null \
	&& stty size </dev/tty | { read -r l c ; echo "$c" ; } \
	&& exit

	command -v ttysize >/dev/null \
	&& ttysize w \
	&& exit

	echo "${COLUMNS:-80}"
)

# =========================================================================

# +++
#
# *tee* and *cap* are plumbing fittings. If the first one is used to
# change direction of pipes, the second one is used to stop flowing
# long lines out of a terminal width.
#
# ---

# =========================================================================

# EOF
