#!/bin/sh

# +++
#
# Transpose a table
#
#     $ printf '%s %s\n' 1 2 3 4 5 6 | ./transpose
#     1 3 5
#     2 4 6
#
# ---

transpose() {
	awk '
{
	for (i = 1; i <= NF; i++) a[NR,i] = $i
}

NF > p { p = NF }

END {
	for (j = 1; j <= p; j++) {
		str = a[1,j]
		for (i = 2; i <= NR; i++) str = str OFS a[i,j]
		print str
	}
}'
}

transpose "$@"
