#!/bin/sh

# =========================================================================
#
# Copyright (C) 2026 Ildar Shaimordanov
# MIT License
#
# =========================================================================

[ -t 0 ] && {
	echo "\
Unwrap lines beginning with a single space
Usage:
... | unwrap
unwrap < FILE"
	exit 1
}

# =========================================================================

awk -v RS='' '
NR > 1 { print "" }
{
	gsub(/\r/,  "")
	gsub(/\n /, "")
	sub(/\n$/,  "")
	print
}'

# =========================================================================

# +++
#
# Unwrap lines beginning with a single space.
# Useful for unwrapping LDIF files.
#
# Example
#
#     ldapsearch ... > FILE
#     unwrap < FILE
#
# ---

# =========================================================================

# EOF
