#!/bin/sh

# =========================================================================
#
# Getting both internal and external IP addresses used for outgoing 
# Internet connections.
#
# Internal IP address is the IP address of your computer network interface 
# that would be used to connect to Internet.
#
# External IP address is the IP address that is visible by external 
# servers that you connect to over Internet.
#
# Copyright (C) 2016-2024 Ildar Shaimordanov
#
# =========================================================================

# Details of the actual implementation are based on the following QA:
#
# How can I get my external IP address in a shell script?
# http://unix.stackexchange.com/q/22615
#
# How do I find my internal ip address?
# https://askubuntu.com/a/604691

# =========================================================================

# Load settings

for f in \
	"$( dirname "$0" )/myip.conf" \
	~/.myip.conf \
	/etc/myip.conf
do
	[ -f "$f" ] && {
		# shellcheck source=/dev/null
		. "$f"
		break
	}
done

# =========================================================================

show_usage() {
	echo "\
USAGE
  $( basename "$0" ) [OPTIONS]

DESCRIPTION
  Display the internal and external IP addresses

OPTIONS
  -i  Display the internal IP address
  -e  Display the external IP address
  -v  Turn on verbosity
  -h  Print this help and exit
"
	exit
}

# =========================================================================

die() {
	warn "$*"
	exit 2
}

warn() {
	echo "$*" >&2
}

# =========================================================================

# Set defaults

# Use Google's public DNS to resolve the internal IP address
[ -n "$TARGETADDR" ] || TARGETADDR="8.8.8.8"

# Query the specific URL to resolve the external IP address
[ -n "$IPURL" ] || IPURL="ipecho.net/plain"

# Define explicitly $IPCMD to gather $IPURL using another tool
[ -n "$IPCMD" ] || {
	if   which curl >/dev/null 2>&1
	then
		IPCMD="curl -s"
	elif which wget >/dev/null 2>&1
	then
		IPCMD="wget -qO -"
	else
		die "Neither curl nor wget installed"
	fi
}

# =========================================================================

# Parse options

show_internal=""
show_external=""
show_verbose=""

while getopts ":ievh" opt
do
	case "$opt" in
	i )
		show_internal=1
		;;
	e )
		show_external=1
		;;
	v )
		show_verbose=1
		;;
	h )
		show_usage
		;;
	\? )
		die "Illegal option: $OPTARG"
		;;
	esac
done

if [ -z "$show_internal" ] && [ -z "$show_external" ]
then
	show_internal=1
	show_external=1
fi

# =========================================================================

# Functions definitions

resolveip() {
	{
		gethostip -d "$1" && return
		getent ahostsv4 "$1" \
		| awk '/RAW/ { print $1; exit }'
	} 2>/dev/null
}

internalip() {
	[ -n "$show_verbose" ] && printf "Internal: "

	case "$( uname | tr '[:upper:]' '[:lower:]' )" in
	cygwin* | mingw* | msys* | win* )
		netstat -rn \
		| awk '$1 == "0.0.0.0" { print $4 }'
		return
		;;
	esac

	t="$( resolveip "$TARGETADDR" )"
	[ -n "$t" ] || {
		warn "Cannot resolve $TARGETADDR"
		return
	}

	ip route get "$t" \
	| sed -n 's/.* src \([^ ]*\) .*/\1/p'
}

externalip() {
	[ -n "$show_verbose" ] && printf "External: "

	# Some resources return their results without a newline and our
	# final result looks not so good. That's the reason why we do
	# echo from subshell - it guarantees printing a newline after
	# an external IP address.
	echo "$( eval "$IPCMD '$IPURL' $IPOPEN" )"
}

# =========================================================================

# Main part

[ -n "$show_internal" ] && internalip
[ -n "$show_external" ] && externalip

# =========================================================================

# EOF
