#!/bin/sh

# =========================================================================
#
# Repeat the given string the particular number of times
# $1 - string
# $2 - number or repetition
#
# Copyright (C) 2023 Ildar Shaimordanov
#
# =========================================================================

# POSIX-compliant, safe and awful
# shellcheck shell=sh

rep(){
	printf "%${2}s" \
	| sed "s/ /$(
		echo "$1" \
		| sed 's/\\/\\\\/g; s/\//\\\//g'
	)/g"
}

# =========================================================================

rep "$@"

# =========================================================================

# EOF
