#!/usr/bin/env bash

# =========================================================================
#
# Repeat the given string the particular number of times
# $1 - string
# $2 - number or repetition
#
# Copyright (C) 2023 Ildar Shaimordanov
#
# =========================================================================

# This version uses a lot of bashisms
# shellcheck shell=bash

rep() {
	local s
	printf -v s "%${2}s"
	printf '%s' "${s// /$1}"
}

# =========================================================================

rep "$@"

# =========================================================================

# EOF
