#!/bin/sh

# =========================================================================
#
# Repeat the given string the particular number of times
# $1 - string
# $2 - number or repetition
#
# Copyright (C) 2023 Ildar Shaimordanov
#
# =========================================================================

# POSIX-compliant but unsafe: requires escaping for each "/" and "\"
# shellcheck shell=sh

rep() {
	printf "%${2}s" \
	| sed "s/ /${1}/g"
}

# =========================================================================

rep "$@"

# =========================================================================

# EOF
