#!/bin/sh

# ==============================================================================
#
# virt-list-dom-by-net
#
# List all VMs ordered by all networks
#
# Copyright (C) 2024, 2025 Ildar Shaimordanov
# MIT License
#
# ==============================================================================

xpath_network='/domain/devices/interface[@type="network"]/source/@network'
xpath_domname='/domain/name/text()'

# ==============================================================================

virsh list --all --name \
| while read -r n && [ -n "$n" ]
do
	virsh dumpxml "$n" --xpath "$xpath_network | $xpath_domname"
done \
| awk -v RS='\n\n' -v FS='\n\\s+|=?"' '
{ host_list[$3] = host_list[$3] "\n  " $1 }

END { for (name in host_list) print name, host_list[name] }
'

# ==============================================================================

# +++
#
# List all VMs ordered by all networks
#
# Requirements
#
# * virsh
# * awk
#
# Technical details
#
# `virsh dumpxml --xpath` outputs results as follows:
#
#     VM_NAME
#      network="VM_NETWORK"
#
# `awk` reorders and groups data accordingly network names:
#
#     VM_NETWORK
#       VM_NAME
#
# ---

# ==============================================================================

# EOF
