#!/bin/sh

# =========================================================================

print_usage() {
	echo "\
Usage: ... | tee-now [OPTIONS] [LABEL]
Copy standard input to a file named 'LABEL-YYYY-mm-dd-HH-MM-SS.log'.
If no LABEL is specified, defaults to 'tee'.

Options
	-a		Append to the file, don't overwrite
	-i		Ignore an interrupt signal
	-h		Print this help and exit
"
}

main() {
	TEEOPTS=""

	while getopts ":ail:h" arg
	do
		case "$arg" in
		a | i )	TEEOPTS="$TEEOPTS -$arg" ;;
		h )	print_usage ; exit ;;
		* )	warn "Bad option: [$OPTARG]: Skipping" ;;
		esac
	done

	shift $(( OPTIND-1 ))

	TEELABEL="${1:-tee}"
	TEEFILE="$TEELABEL-$( date '+%Y-%m-%d-%H-%M-%S' ).log"

	trap 'rm_empty' EXIT

	warn "Store to file: $TEEFILE"

	unbuf="$( command -v stdbuf )"
	# shellcheck disable=SC2086
	${unbuf:+$unbuf -i0 -o0 -e0} tee $TEEOPTS "$TEEFILE"
}

# =========================================================================

rm_empty() {
	if [ -s "$TEEFILE" ]
	then
		warn "Stored to file: $TEEFILE"
	else
		warn "Remove empty file: $TEEFILE"
		rm -f "$TEEFILE"
	fi
}

warn() {
	echo "$*" >&2
}

# =========================================================================

main "$@"

# =========================================================================

# EOF
